version: '2'
services: 
  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: "users"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    networks:
      - app-network

  pg-admin:
    container_name: db-admin-container
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "8081:80"
    depends_on: 
      - postgres
    volumes:
      - ./util:/data
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin
      PGADMIN_DEFAULT_PASSWORD: p@ssword
    networks:
      - app-network

  users:
    build: 
      context: users
    image: users-ms-bootcamp
    container_name: users-ms-bootcamp-container
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      TYPEORM_CONNECTION: "postgres"
      TYPEORM_HOST: "postgres"
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: "postgres"
      TYPEORM_PASSWORD: "password"
      TYPEORM_DATABASE: "users"
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "true"
      TYPEORM_ENTITIES: "./dist/**/*.entity.js"
      TOKEN_SECRET: "NDgzMDE2MDIzNDQwNjIxNjE4.DmNiFQ.C9hWQsCEJoW5Y9mT5oatUjSLKlw"
      TOKEN_EXPIRATION_TIME: 3600
    networks:
      - app-network

networks:
  app-network:
    driver: bridge      